apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-lint-pipeline
spec:
  tasks:
    - name: git-clone
      params:
        - name: url
          value: "https://github.com/upslopeio/lint-markdown-files.git"
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: lint-markdown
      taskRef:
        name: markdown-lint
      runAfter:
        - git-clone
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
      params:
        - name: args
          value: ["."]
  workspaces:
    - name: shared-workspace